[en]
LanguageName = "🇬🇧 EN"
description = "Ph.D. in cognitive robotics for human/robot collaboration"
copyright = "{{ YEAR }}-François Hélénon. Powered by [Hugo](https://gohugo.io/) and [Anatole](https://github.com/lxndrblz/anatole/) theme"
title = "François Hélénon"
weight = 1
locale="en-us"
contentDir="content/en"
cvPath="https://drive.google.com/uc?export=download&id=1RZegOJIQZXBngoUr1W-5Oqkp4ieRofmn"


[fr]
LanguageName = "🇫🇷 FR"
title = "François Hélénon"
copyright = "{{ YEAR }}-François Hélénon. Produit via [Hugo](https://gohugo.io/) et le thème [Anatole](https://github.com/lxndrblz/anatole/)"
description = "Ph.D. en robotique cognitive pour la collaboration homme-robot"
weight = 1
locale="fr-fr"
contentDir="content/fr"
cvPath="https://drive.google.com/uc?export=download&id=1lLKwqZgP7-DQZry5wU7a_IxOoAjl2sXS"